{
 "title": "WAN WLAN Performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Ping Zeiten",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "alias": "www.google.ch LAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"latency_ms\") FROM \"ping_latency\" WHERE $timeFilter AND \"host\"='www.google.ch' AND \"interface\"='eth0' GROUP BY time(1m) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bandwidth_mbps::field", "operator": "=", "value": "select tag value" }
     ]
    },
    {
     "alias": "www.google.ch WLAN",
     "query": "    SELECT mean(\"latency_ms\") FROM \"ping_latency\" WHERE $timeFilter AND \"host\"='www.google.ch' AND \"interface\"='wlan0' GROUP BY time(1m) fill(null)\n"
    },
    {
     "alias": "wiki.bzz.ch LAN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"latency_ms\") FROM \"ping_latency\" WHERE $timeFilter AND \"host\"='wiki.bzz.ch' AND \"interface\"='eth0' GROUP BY time(1m) fill(null)\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "bandwidth_mbps::field", "operator": "=", "value": "select tag value" }
     ]
    },
    {
     "alias": "wiki.bzz.ch WLAN",
     "query": "    SELECT mean(\"latency_ms\") FROM \"ping_latency\" WHERE $timeFilter AND \"host\"='wiki.bzz.ch' AND \"interface\"='wlan0' GROUP BY time(1m) fill(null)\n"
    }
   ]
  },
  {
   "title": "Download Performance",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "alias": "Download WLAN",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "download_test",
     "select": [
      [
       { "params": [ "bandwidth_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "interface::tag", "operator": "=", "value": "wlan0" }
     ]
    },
    {
     "alias": "Download LAN",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "download_test",
     "select": [
      [
       { "params": [ "bandwidth_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "interface::tag", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "Speedtest Download LAN",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "download_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "interface::tag", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "Speedtest Upload LAN",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "upload_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "interface::tag", "operator": "=", "value": "eth0" }
     ]
    },
    {
     "alias": "Speedtest Download WLAN",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "download_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "interface::tag", "operator": "=", "value": "wlan0" }
     ]
    },
    {
     "alias": "Speedtest Upload WLAN",
     "groupBy": [
      { "params": [ "5m" ], "type": "time" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "upload_mbps" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "interface::tag", "operator": "=", "value": "wlan0" }
     ]
    }
   ]
  },
  {
   "title": "Download Performance 5,50,80 Mb from it.bzz.ch",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "query": "  SELECT mean(\"duration_seconds\") FROM \"download_test\" WHERE $timeFilter GROUP BY time(5m), \"file\", \"interface\" fill(null)\n"
    }
   ]
  }
 ]
}